# Generated by Django 5.1.5 on 2025-02-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='DOB',
            field=models.DateField(),
        ),
    ]
